name: firebase_messaging_example
description: Demonstrates how to use the firebase_messaging plugin.

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5 <2.0.0"

dependencies:
  firebase_core: ^0.8.0-nullsafety.1
  firebase_messaging: ^9.0.0-1.0.nullsafety.0
  flutter:
    sdk: flutter
  flutter_local_notifications: ^3.0.0
  http: ^0.12.2

dependency_overrides:
  firebase_core: ^0.8.0-nullsafety.1
  firebase_core_platform_interface: ^4.0.0-nullsafety.0
  firebase_core_web: ^0.3.0-nullsafety.0
  firebase_messaging:
    path: ../
  firebase_messaging_platform_interface: ^2.0.0-1.0.nullsafety.0
  http_parser: ^4.0.0-nullsafety

dev_dependencies:
  drive: 0.0.1-6.0.pre
  flutter_driver:
    sdk: flutter
  test: any

flutter:
  uses-material-design: true
